# ----------------------------------------------- #
# This module was generated by 'generator' tool . #
# See 'tools/generator'.                          #
# ----------------------------------------------- #

import ../base
import bank/bank_en_GH
import bank/bank_en_US
export base

proc bankCountry*(f: Faker): string =
  ## Generates random bankCountry.
  runnableExamples:
    let f = newFaker()
    echo f.bankCountry()

  case f.locale
  of "en_GH": bank_en_GH.bankCountry(f)
  of "en_US": bank_en_US.bankCountry(f)
  else: bank_en_US.bankCountry(f)

proc bban*(f: Faker): string =
  ## Generates random bban.
  runnableExamples:
    let f = newFaker()
    echo f.bban()

  case f.locale
  of "en_GH": bank_en_GH.bban(f)
  of "en_US": bank_en_US.bban(f)
  else: bank_en_US.bban(f)

proc iban*(f: Faker): string =
  ## Generates random iban.
  runnableExamples:
    let f = newFaker()
    echo f.iban()

  case f.locale
  of "en_GH": bank_en_GH.iban(f)
  of "en_US": bank_en_US.iban(f)
  else: bank_en_US.iban(f)
